### ISSUE TITLE
silent to statement?

### ISSUE THREAD

**Issue by MoritzFago** [svarshavchik/courier#2]
If i use the to or cc statement to (re-)deliver a mail it adds a received field in the email, this isn't always wanted, because some mail clients use the last received field as the source for the time of receive. This isn't wanted if you use mail drop to redeliver mail after spam training.

How can i suppress that additional header field?

**Comment by svarshavchik** [comment]
The purpose of the Received: header is to prevent mail loops. Although it's purpose is not to provide the time mail got delivered, redelivering mail means that, technically, mail gets delivered again, so the recorded timestamp is technically correct.

maildrop has no knowledge of where the mail goes. All it does is submit the message for delivery, and the mail server then figures out where the mail goes. The Received: header is not added by maildrop, but by the mail server, which has no knowledge of the intentions and the original reason why the mail got sent. To the mail server, it is no different then any other message that needs to be delivered; which includes recording the appropriate Received: header in order to prevent mail loops.
